### ISSUE TITLE
Headless mode: not all endpoints are working 

### ISSUE THREAD

**Issue by mrosseel** [mrosseel/bisq-api#13]
copied from #6 :

I have:
- Upgraded Java to 1.8.0_162
- Deleted ~/.m2 (maven)
- Pulled latest from bisq-api and bisq-network/exchange
- recompiled everything

```
BISQ_API_PORT=2223 mvn -X exec:java -Dexec.mainClass="io.bisq.api.app.ApiMain" -Dexec.args="--baseCurrencyNetwork=BTC_REGTEST --bitcoinRegtestHost localhost --nodePort 2222 --useLocalhost true --appName Bisq-Regtest-Bob --seedNodes=localhost:2002" 
```
now gives:
```
Apache Maven 3.5.0
Maven home: /usr/share/maven
Java version: 1.8.0_162, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk1.8.0_162/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.13.0-25-generic", arch: "amd64", family: "unix"
```
and the API starts up in headless mode without giving any error:
```
#################################################################
Connected to node: localhost:2002
Received 0 instances
#################################################################
INFO  [2018-01-19 14:58:22,724] io.bisq.core.app.AppSetupWithP2P: onRequestingDataCompleted
INFO  [2018-01-19 14:58:22,724] io.bisq.core.app.AppSetupWithP2P: onBasicServicesInitialized
INFO  [2018-01-19 14:58:23,059] io.bisq.network.p2p.peers.getdata.RequestDataHandler: We send a GetUpdatedDataRequest to peer localhost:2002. 
INFO  [2018-01-19 14:58:23,064] io.bisq.core.app.AppSetupWithP2P: onHiddenServicePublished
INFO  [2018-01-19 14:58:23,080] io.bisq.network.p2p.peers.getdata.RequestDataHandler: 
#################################################################
Connected to node: localhost:2002
Received 0 instances
#################################################################
INFO  [2018-01-19 14:58:23,080] io.bisq.core.app.AppSetupWithP2P: onBootstrapComplete
INFO  [2018-01-19 14:58:23,082] io.bisq.core.app.AppSetupWithP2P: onRequestingDataCompleted
INFO  [2018-01-19 14:58:32,655] io.bisq.network.p2p.peers.PeerManager: We have 1 connections open. Our limit is 12
```

# However: #
`http://localhost:2223/swagger` is available in my browser, but very little of the endpoints are working.

### What works: ###
- offer_list
- offer_detail
- market_list
- currency_list

### What does not: ###
- **wallet_addresses**: returns `200` and an empty array, even though I have wallets set up
- **account_list**: same as `wallet_addresses'
- **wallet_detail**: returns `204 undocumented`, Response Headers: `date: Fri, 19 Jan 2018 15:01:25 GMT `
- **trade_list**: returns `500 Error: Internal Server Error` 
```
{
  "code": 500,
  "message": "There was an error processing your request. It has been logged (ID a960949befe1e87e)."
}
```
- **trade_detail** with valid id: Same as `trade_list`
- **wallet_tx_list** : Same as `trade_list`

### Untested: ###
- offer_cancel
- offer_make
- offer_take
- payment_started
- payment_received
- move_funds_to_bisq_wallet

**Everything however works in GUI mode**
When I start with `io.bisq.api.app.BisqApiWithUIMain`, all the tested API endpoints work as expected.

Additional logging for `500` errors:
```
ERROR [2018-01-19 15:13:21,164] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: a960949befe1e87e
! java.lang.NullPointerException: null
! at io.bisq.core.trade.TradeManager.getTradableList(TradeManager.java:513)
! at io.bisq.api.BisqProxy.getTradeList(BisqProxy.java:520)
! at io.bisq.api.service.ApiResourceV1.tradeList(ApiResourceV1.java:222)
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:34)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:241)
! at io.dropwizard.jetty.ContextRoutingHandler.handle(ContextRoutingHandler.java:38)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:527)
! at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:68)
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at org.eclipse.jetty.server.Server.handle(Server.java:561)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104)
! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
! at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
! at java.lang.Thread.run(Thread.java:748)
```

**Comment by mrosseel** [comment]
Quite some changes to fix these, let me know if it works for you now!

**Comment by citkane** [comment]
I pulled latest and recompiled on 1.8.0_162:
## What works: ##
- trade_list
- trade_detail
- account_list
- currency_list
- market_list
- wallet_detail
- wallet_addresses
- wallet_tx_list

## What works partially: ##
**offer_make** for "FIXED" works:
```
http://localhost:3123/api/v1/offer_make?payment_account_id=97f0ff19-3854-4a72-b459-d3ceeecddefb&direction=BUY&price_type=FIXED&market_pair=XMR_BTC&percentage_from_market_price=0&fixed_price=2941176&amount=100000000&min_amount=100000000

200:true
```


**offer_make** for "PERCENTAGE" does not:
```
http://localhost:3123/api/v1/offer_make?payment_account_id=97f0ff19-3854-4a72-b459-d3ceeecddefb&direction=BUY&price_type=PERCENTAGE&market_pair=XMR_BTC&percentage_from_market_price=0&fixed_price=0&amount=100000000&min_amount=100000000

{
  "code": 500,
  "message": "Error while placing offer:An error occurred at task: ValidateOffer\nException message: Price is null"
}
```


## What does not work ##

**offer_list**
The default swagger parameters (This error is in headless and GUI mode):
```
http://localhost:3123/api/v1/offer_list?market=all&status=all&whose=all&start=0&end=9223372036854776000&limit=100

{
  "code": 404,
  "message": "HTTP 404 Not Found"
}
```

Without parameters:
```
http://localhost:3123/api/v1/offer_list

200:[]
```
However, I have a number of offers open which get listed in GUI mode



**offer_detail**
```
http://localhost:3123/api/v1/offer_detail?offer_id=1a3e9140-929f-4a9e-a0e0-a0f4ca5af77a

{
  "code": 500,
  "message": "There was an error processing your request. It has been logged (ID 03de2b6c3984023b)."
}
```



**offer_take**
```
http://localhost:3123/api/v1/offer_take?offer_id=1dfea1ab-e4f8-42d5-8d39-868fe620cfd2&payment_account_id=97f0ff19-3854-4a72-b459-d3ceeecddefb%20&amount=100000000

{
  "code": 500,
  "message": "Unknown offer id"
}
```
However, the offer id is valid.



**offer_cancel**
```
http://localhost:3123/api/v1/offer_cancel?offer_id=29848ebb-3cfa-4c6f-9b04-7a52414d7a49

{
  "code": 500,
  "message": "There was an error processing your request. It has been logged (ID 329c0aefb277e99d)."
}
```



**payment_started**
```
http://localhost:3123/api/v1/payment_started?trade_id=6a874bdf-1344-4c49-b11c-b93e33b4ba55

{
  "code": 500,
  "message": "Toolkit not initialized"
}
```



**payment_received**
```
http://localhost:3123/api/v1/payment_received?trade_id=771e4e37-4b64-45ca-83ee-3ff0bac64543

{
  "code": 500
}
```



**move_funds_to_bisq_wallet**
```
http://localhost:3123/api/v1/move_funds_to_bisq_wallet?trade_id=6a874bdf-1344-4c49-b11c-b93e33b4ba55

{
  "code": 500,
  "message": "There was an error processing your request. It has been logged (ID ab79aff3a0ba905a)."
}
```

**Comment by mrosseel** [comment]
* offer_make price is null should have been fixed in #16 , could you check you have that commit?
* offer_list is working, but the default swagger value of 9223372036854776000 is wrong. The max is actually 9223372036854775807 but swagger keeps rounding it. Just change it manually for now
* offer_detail is working fine here, if you could add the logging output that would maybe help

Still have to test the rest. One of the tickets is #10 - write integration tests. That should catch most of these regressions.

**Comment by citkane** [comment]
https://github.com/mrosseel/bisq-api/issues/16 has fixed the **offer_make** issue

**offer_list** is working partially. This is the behaviour pattern:
- I create offers in GUI mode. "offer_list" returns these correctly in GUI mode.
- I restart the API in headless mode. "offer_list" returns an empty array `200:[]` (no error is thrown)
- I create offers in headless mode.  "offer_list" returns only these offers (created in headless) in the array.
- I restart the API in GUI mode. "offer_list" returns all offers (created in headless and GUI)
- I restart the API in headless mode. "offer_list" goes back to an empty array `200:[]` (no error is thrown)
- I create more offers in headless mode, which are returned properly by "offer_list".
- I restart the API (still) in headless mode, and the offers are again gone. "offer_list" returns an empty array `200:[]`.

I deduce: **Offers created in headless mode do not persist across headless restarts, but show in GUI sessions and persist across GUI restarts**

**offer_detail** in headless mode works for offer ids that have not yet "disappeared" as described above. If I try to look up an id (which shows in GUI but not headless) I get the following error:
```
ERROR [2018-01-24 19:29:50,503] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: fae47f3feb6f1397
! java.util.NoSuchElementException: No value present
! at java.util.Optional.get(Optional.java:135)
! at io.bisq.api.BisqProxy.getOfferDetail(BisqProxy.java:184)
! at io.bisq.api.service.ApiResourceV1.offerDetail(ApiResourceV1.java:138)

```

**Comment by mrosseel** [comment]
* glad about #16 
* interesting observation, I will try to recreate this

thanks for your patience, being the first real user has its downsides ;)

**Comment by citkane** [comment]
No worries @mrosseel , we will get there! I remain excited about the potential for BISQ and the upsides of being the first real user of the API.
